image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: |
     pip3 install cookiecutter
     read -p "project_name: " projectvar
     cookiecutter gh:cookiecutter/cookiecutter-django
     cd $projectvar
     python3 -m venv env
     source env/bin/activate
     pip3 install -r requirements/local.txt
     echo 'ALLOWED_HOSTS+=["*"]' >> config/settings/local.py
    
    #cd <what you have entered as the project_slug at setup stage> 
    #pip install -r requirements/local.txt
    
    command: |
      python manage.py runserver
    
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:  
  - name: Django
    port: 8000    
    visibility: private    
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:  
  extensions:    
  - ms-python.python